version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-music-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./config.py:/app/config.py
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 