[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.pip"]

[phases.install]
cmds = ["chmod +x railway-build.sh", "./railway-build.sh"]

[phases.build]
cmds = ["echo 'Build completed successfully!'"]

[start]
cmd = "python main.py"
