[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.pip", "python311Packages.pipenv"]

[phases.install]
cmds = ["pipenv install --deploy"]

[phases.build]
cmds = ["echo 'Build completed successfully!'"]

[start]
cmd = "pipenv run python main.py"
