[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.discordpy", "python311Packages.yt-dlp", "python311Packages.pynacl", "python311Packages.python-dotenv"]

[phases.install]
cmds = ["echo 'Dependencies installed via nixPkgs'"]

[phases.build]
cmds = ["echo 'Build completed successfully!'"]

[start]
cmd = "python main.py"
