[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.pip"]

[phases.install]
cmds = ["chmod +x start.sh"]

[phases.build]
cmds = ["echo 'Build completed successfully!'"]

[start]
cmd = "./start.sh"
