[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed successfully!'"]

[start]
cmd = "python main.py"
