[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["python -m venv venv", "venv/bin/pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed successfully!'"]

[start]
cmd = "venv/bin/python main.py"
