[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = ["pip install --user -e ."]

[phases.build]
cmds = ["echo 'Build completed successfully!'"]

[start]
cmd = "python main.py"
