[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --user --break-system-packages --no-cache-dir -r requirements.txt", "echo 'Installation completed!'"]

[phases.build]
cmds = ["echo 'Build completed successfully!'", "pip list --user", "echo 'Ready to start!'"]

[start]
cmd = "python main.py"
