services:
  - type: web
    name: fvq-songs
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONHTTPSVERIFY
        value: "0"
      - key: RENDER_SERVICE_NAME
        value: "fvq-songs"
      - key: PORT
        value: "8080"
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    numInstances: 1
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1