services:
  - type: web
    name: discord-music-bot
    env: docker
    plan: free
    buildCommand: docker build -t discord-bot .
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11
      - key: KEEP_ALIVE_URL
        value: https://discord-music-bot.onrender.com
      - key: PORT
        value: 8080
    healthCheckPath: /health
    autoDeploy: true 